apiVersion: eks.amazonaws.com/v1
kind: IngressClassParams
metadata:
  name: openclaw-alb
spec:
  scheme: internet-facing
  certificateARNs:
    - arn:aws:acm:ap-northeast-1:914945738914:certificate/4762bb43-dbf9-4994-9846-d9ad57f06663
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: openclaw
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: openclaw-alb
spec:
  controller: eks.amazonaws.com/alb
  parameters:
    apiGroup: eks.amazonaws.com
    kind: IngressClassParams
    name: openclaw-alb
